# Activity: The "Hospital Pharmacy Inventory Manager"

### Activity Type:
Online

### Objective:
To master the end-to-end data workflow including loading external datasets, handling missing values, performing data cleaning, creating new features, filtering records, generating analytical reports, and exporting cleaned data.

---

## Steps

### 1. File Creation & Loading

- Use **medicine_inventory.csv**.
- Load the file into a DataFrame using `pd.read_csv()`.

---

### 2. Initial Exploration

- Display the first **5** rows and the last **2** rows of the dataset.
- Check the number of missing values in the **Price** and **Quantity** columns.

---

### 3. Data Cleaning

- Fill the missing values in **Price** with the **mean (average) price**.
- Fill any missing values in **Quantity** with **1**.

---

### 4. Feature Engineering

- Create a new column called **Inventory_Value** using the following formula:

> **Inventory_Value = Price × Quantity**

---

### 5. Filtering & Slicing

#### Boolean Filtering

Create a new DataFrame called **well_stocked** that contains medicines with a **Quantity of 15 or more**.

#### loc Selection

Display rows **5 to 10** and show only the following columns:

- Medicine
- Inventory_Value

---

### 6. Reporting

Use `.describe()` to generate a statistical summary of the **Inventory_Value** column.

---

### 7. Final Step

Save the cleaned dataset into a new CSV file called:

`cleaned_medicine_inventory.csv`

using the `.to_csv()` method.

In [4]:
# import the Libraries 
import pandas as pd

In [5]:
# load the dataset
path =r'D:\NTI-ML\nti-projects\Medicine-analysis\Medicine.csv'
df = pd.read_csv(path)

In [7]:
#Display the first 5 rows of the dataset 
df.head()

      Medicine  Price  Quantity     Category
0  Paracetamol   25.0      20.0  Pain Relief
1    Ibuprofen   35.0       NaN  Pain Relief
2  Amoxicillin   80.0      12.0  Antibiotics
3    Vitamin C   50.0      30.0  Supplements
4      Insulin    NaN       5.0     Diabetes

In [8]:
#Checking the number of missing value in Price and Quantity columns
df.isnull().sum()

Medicine    0
Price       1
Quantity    3
Category    0
dtype: int64

In [9]:
#fil the missing vlue in the price with the mean 
df['Price'].fillna(df['Price'].mean(), inplace=True)

C:\Users\user\AppData\Local\Temp\ipykernel_24224\4211558057.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Price'].fillna(df['Price'].mean(), inplace=True)

In [11]:
#Display the price column after filling the missing value with the mean
df['Price'].head()

0    25.000000
1    35.000000
2    80.000000
3    50.000000
4    61.785714
Name: Price, dtype: float64

In [12]:
#Fill any misssing vlue in the Quantity column with 1
df['Quantity'].fillna(1, inplace=True)

C:\Users\user\AppData\Local\Temp\ipykernel_24224\136146805.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Quantity'].fillna(1, inplace=True)

In [ ]:
# Display the Quantity column after filling the missing value with 1
df['Quantity']

0      20.0
1       1.0
2      12.0
3      30.0
4       5.0
5       8.0
6      15.0
7       1.0
8      50.0
9      25.0
10    100.0
11      6.0
12      1.0
13     18.0
14     22.0
Name: Quantity, dtype: float64

In [14]:
#Create a new column called Inventory_Value by inventory_value =price * quantity
df['Inventory_Value'] = df['Price'] * df['Quantity']

In [15]:
#Check the data after the changes
df.head()

      Medicine      Price  Quantity     Category  Inventory_Value
0  Paracetamol  25.000000      20.0  Pain Relief       500.000000
1    Ibuprofen  35.000000       1.0  Pain Relief        35.000000
2  Amoxicillin  80.000000      12.0  Antibiotics       960.000000
3    Vitamin C  50.000000      30.0  Supplements      1500.000000
4      Insulin  61.785714       5.0     Diabetes       308.928571

In [16]:
#Create a new DataFrame called well_stocked that contains medicines with a Quantity of 15 or more 
well_stocked = df[df['Quantity'] >= 15]
well_stocked

               Medicine  Price  Quantity     Category  Inventory_Value
0           Paracetamol   25.0      20.0  Pain Relief            500.0
3             Vitamin C   50.0      30.0  Supplements           1500.0
6               Antacid   30.0      15.0    Digestive            450.0
8              Bandages   10.0      50.0    First Aid            500.0
9        Hand Sanitizer   20.0      25.0      Hygiene            500.0
10            Face Mask    5.0     100.0      Hygiene            500.0
13  Glucose Test Strips   90.0      18.0     Diabetes           1620.0
14        Multivitamins   40.0      22.0  Supplements            880.0

In [18]:
#iloc selection 
#Display row 5 ot 10 and show only the following columns [Medicine , inventory_value]
df.iloc[5:11, [0, 3]]

          Medicine    Category
5      Cough Syrup  Cold & Flu
6          Antacid   Digestive
7        Eye Drops    Eye Care
8         Bandages   First Aid
9   Hand Sanitizer     Hygiene
10       Face Mask     Hygiene

In [20]:
#Reorting 
df[['Inventory_Value']].describe()

       Inventory_Value
count        15.000000
mean        619.261905
std         460.636769
min          35.000000
25%         379.464286
50%         500.000000
75%         800.000000
max        1620.000000

In [21]:
#Save the cleaned data to a new CSV file named cleaned_medicine_inventory.csv
df.to_csv('cleaned_medicine_inventory.csv', index=False)